name: my_fun_project
target-path: target
clean-targets: [target, dbt_packages]

packages-install-path: dbt_packages

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
asset-paths: ["assets"]

query-comment: 'this is my super cool project'

flags:
  fail_fast: true

quoting:
  database: false
  schema: false
  identifier: false

models:
  my_fun_project:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: ephemeral

vars:
  start_date: "2025-01-01"
  max_count_value: 30
  string_value: "HeyHoHi"
