name: jaffle_shop_sweets
version: '1.0.0'
config-version: 2

profile: my-snowflake-db

target-path: target
clean-targets: [target, dbt_packages]

packages-install-path: dbt_packages

require-dbt-version: [">1.0.0", "<=1.9.2"]

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
asset-paths: ["assets"]

query-comment: 'this is my super cool project'

flags:
  fail_fast: true

quoting:
  database: false
  schema: false
  identifier: false

models:
  jaffle_shop_sweets:
    marts:
      +required_tests: {"unique.*|not_null": 1}
      +materialized: table
      +schema: dbo
    intermediate:
      +materialized: ephemeral

vars:
  start_date: "2025-01-01"
  max_count_value: 30
  string_value: "HeyHoHi"

on-run-start: SELECT 1
on-run-end: SELECT 1

restrict-access: false